### ISSUE TITLE
NPE in loading default world with custom loader

### ISSUE THREAD

**Issue by DartCZ** [Paul19988/Advanced-Slime-World-Manager#102]
**Describe the issue**
While loading main world, we have this error:
![image](https://user-images.githubusercontent.com/8595779/153719303-3386a78f-c3f5-4b67-a2e9-964319a616c9.png)

![image](https://user-images.githubusercontent.com/8595779/153719299-c5660e9e-aab9-48a2-a475-cea3d5a4904f.png)

worlds.yml
![image](https://user-images.githubusercontent.com/8595779/153719399-4256f9f1-18f5-4c19-8f84-d0fb3960b931.png)

**Spigot version**
Paper 1.18.1 build 194

**Plugin version**
Latest experimental from 1.18 branch.

**How to reproduce**
Load this world on startup with custom loader https://cdn.discordapp.com/attachments/587350089970745411/942091994514210916/world.slime

It should be noted that we load main world in very hacky way, because we have custom Seaweed loader and for ability to load in startup we must registering it by Logfilter 😄 On 1.17 it works.

For your imagination:
![image](https://user-images.githubusercontent.com/8595779/153719320-0ce0d536-52e2-4736-8a61-888176138b79.png)

**Crash reports (if available)**
Attached in **Describe the issue**

**Comment by ComputerNerd100** [comment]
Thanks @DartCZ 
Please could you upload your latest.log file too - just for ease of referencing the error message :)

**Comment by DartCZ** [comment]
> Thanks @DartCZ Please could you upload your latest.log file too - just for ease of referencing the error message :)

sure, here is it https://paste.survival-games.cz/gisirisoyu.csharp

**Comment by Owen1212055** [comment]
Fixed in https://github.com/Paul19988/Advanced-Slime-World-Manager/pull/97/commits/9833e28298e58dd1061a697a6de0dc5034fc93b7
