### ISSUE TITLE
1.18 - Index OOB Exception for Chunk Read

### ISSUE THREAD

**Issue by ComputerNerd100** [Paul19988/Advanced-Slime-World-Manager#105]
ArrayIndexOutOfBoundsException - SRF Implementation @ Read Chunk Sections New (Line 358)

chunkSectionArray appears to be length 1, implementation trying to assign to index 7 (from var Y - read from data stream, issue with serialization or format potentially?)

MC Ver: 1.18

Plugin Ver: #97 

Crash report: https://discord.com/channels/741733106930810950/741735355262173325/947527209390862416
Crash report: https://discord.com/channels/741733106930810950/741735355262173325/947143316997308476

Reported by:

Haxx#6785
Stitchy#1087

**Comment by ComputerNerd100** [comment]
I think I've narrowed this one down possibly (needs confirmation!)

When serializing the chunks, we write the min section, max section and section count as ints, where section count is a count of all the non-null sections in the chunk column. (CraftSlimeWorld#L343)

We then iterate through the entire sections array with sections,length (CraftSlimeWorld#L348), and skip empty (null) sections with a `continue` call for each null section. We write out `i` for each non-null chunk section.

On the de-serialization side (v1_9SlimeWorldFormat#L312), we declare the chunk section array as a new array with the size of the serialized section count. We then iterate for the length of this array, and read in the chunk section index from the data stream, and use this index (var Y) to write to the array on line 358.

In principle this means that if a chunk column contains a single chunk section at index 7, when we create the section array in deserialization, the array has length 1, yet we're using its original index of 7 to write into the array, causing the AIOOB.

**Comment by Owen1212055** [comment]
Fixed in https://github.com/Paul19988/Advanced-Slime-World-Manager/pull/97/commits/70c448aaae295427ab085641e0cf7abb4b2a9ddb
