### ISSUE TITLE
DEBUG on load WORLD

### ISSUE THREAD

**Issue by aleexgheorghe** [Paul19988/Advanced-Slime-World-Manager#114]
**Describe the issue**
I've tested the latest build [[612a30](https://github.com/Paul19988/Advanced-Slime-World-Manager/commit/612a30d1a4fd6db52370b664350718f1369b2ee1)] **Fix 1.17** on my servers with paper version 1.17.1 and I get a weird debug when loading worlds (not always, just some).

It would be nice if in this case, there is some kind of `swm debug` command or similar to trigger these things instead of blotting the console, as it really is huge.

**Spigot version**
Paper 1.17.1

**Plugin version**
Last build

**How to reproduce**
All this happens when a player loads a world. We can see the debug and logs here: https://paste.minebox.es/icuyebinug.pl

**Comment by Owen1212055** [comment]
Wasn't meant to be pushed, fixed in https://github.com/Paul19988/Advanced-Slime-World-Manager/commit/8da1ce7707fc7fe043b71e37967e84b91ac9e89a 

Ideally we instead use proper logging in the future lol.
