### ISSUE TITLE
Nether and End environments are not supported

### ISSUE THREAD

**Issue by macjuul** [Paul19988/Advanced-Slime-World-Manager#12]
**Describe the issue**
Currently, only overworld worlds are loading in correctly. Nether or end worlds will throw exceptions on load.

![image](https://user-images.githubusercontent.com/7606171/89743572-bedf0500-daa4-11ea-9da7-b774e5372c0b.png)

**Comment by BlueSoapTurtle** [comment]
Issue here
`server = new CustomWorldServer((CraftSlimeWorld) world, dataManager, conversionSession, dimensionManager, env, worldData, worldKey, DimensionManager.OVERWORLD, Arrays.asList(new MobSpawnerCat()), false, true);`
in the createNMSWorld method

**Comment by macjuul** [comment]
Fixed
