### ISSUE TITLE
Server freezes (and crashes) when unloading a Slime world

### ISSUE THREAD

**Issue by TheLukeGuy** [Paul19988/Advanced-Slime-World-Manager#123]
**Describe the issue**
Unloading a Slime world causes the server to completely freeze and eventually crash. The issue seems to happen when the world is being saved, but it only happens when the world is being unloaded. It does not occur when `/save-all` is run.

**Spigot version**
Paper 1.18.2, build 333

**Plugin version**
```
> ver slimeworldmanager
[22:02:46 INFO]: SlimeWorldManager version ${project.version}
```
(2.8.0 according to the JAR name)

**How to reproduce**
1. `/swm create test file`
2. `/swm unload test`
3. Watch the server die :)

**Crash reports (if available)**
[https://www.toptal.com/developers/hastebin/raw/nukiyanigi](https://www.toptal.com/developers/hastebin/raw/nukiyanigi)

**Comment by Owen1212055** [comment]
Update your class modifier.

**Comment by TheLukeGuy** [comment]
> Update your class modifier.

Hmm, not quite sure what you mean? This happens with the plugin alone too, not only when using the API.

**Comment by Owen1212055** [comment]
https://github.com/Paul19988/Advanced-Slime-World-Manager/blob/develop/.docs/usage/install.md

**Comment by TheLukeGuy** [comment]
Oh, that's embarrassing, I'm not sure how I missed that. Sorry about that, thanks for your help!
