### ISSUE TITLE
Cannor resolve flow-nbt

### ISSUE THREAD

**Issue by arthurr0** [Paul19988/Advanced-Slime-World-Manager#124]
```xml
    <dependency>
      <groupId>com.grinderwolf</groupId>
      <artifactId>slimeworldmanager-api</artifactId>
      <version>2.8.0-20220512.200618-18</version>
    </dependency>
```
   **Error:** Unresolved dependency: 'com.flowpowered:flow-nbt:jar:2.0.2'

**Comment by ComputerNerd100** [comment]
@arthurr0 Please add the rapture releases repository to your POM: https://repo.rapture.pw/repository/maven-releases/
We ship Flow NBT 2.0.2 from there :)

**Comment by arthurr0** [comment]
Ohh well! I had /maven-snapshots added and didn't notice
