### ISSUE TITLE
Wrong worldversion

### ISSUE THREAD

**Issue by BlueSoapTurtle** [Paul19988/Advanced-Slime-World-Manager#13]
in the v1_16_R1SlimeNMS class, the variable is defined below as:
`private final byte worldVersion = 0x05`

but in the WorldImporter.java we see that 
`worldVersion = 0x05; // 1.14 world`

Making me feel that the worldVersion in 1_16 should be 0x07
but we should change the importer to handle 1.15 and 1.16 as well

**Comment by Paul19988** [comment]
Fixed in Commit https://github.com/Paul19988/Advanced-Slime-World-Manager/commit/ef80093b733082bd98480ed1625271e4bba659ed
