### ISSUE TITLE
Dependency Unresolved

### ISSUE THREAD

**Issue by plytki** [Paul19988/Advanced-Slime-World-Manager#142]
**Describe the issue**
I added repo and dependency and I get this error. `Unresolved dependency: 'com.flowpowered:flow-nbt:jar:2.0.2'`
**Spigot version**
1.18.1
**Plugin version**
2.8.0-SNAPSHOT
**How to reproduce**
I'm using Maven I can't say if there will be the same problem as with me.
**Crash reports (if available)**

**Comment by b0ykoe** [comment]
Add this to your pom.xml
```xml
<repository>
    <id>rapture-releases</id>
    <url>https://repo.rapture.pw/repository/maven-releases/</url>
  </repository>

<dependency>
    <groupId>com.flowpowered</groupId>
    <artifactId>flow-nbt</artifactId>
    <version>2.0.2</version>
  </dependency>
```
