### ISSUE TITLE
1.19.3 Version Support

### ISSUE THREAD

**Issue by Zsomi** [Paul19988/Advanced-Slime-World-Manager#165]
**Is your feature request related to a problem? Please describe.**
You could say it's a problem since the server is on version 1.19.3 which is not yet supported by the plugin.

**Describe the solution you'd like**
The solution would be to make AdvancedSlimeWorldManager support minecraft 1.19.3.

**Comment by Paul19988** [comment]
Unsupported version.

**Comment by Zsomi** [comment]
Will this not be done at all in the future?

**Comment by Paul19988** [comment]
The intention is to form a paper patch as it'll be easier than the way we currently operate with ASWM

**Comment by Zsomi** [comment]
So this version will never be supported in the ASWM plugin?

**Comment by tatteaid** [comment]
> So this version will never be supported in the ASWM plugin?

No, it probably will be supported, whenever they get around to finishing the paper patch.
