### ISSUE TITLE
Error with SSW extension (SSW have this as expansion)

### ISSUE THREAD

**Issue by TheExotik** [Paul19988/Advanced-Slime-World-Manager#170]
I've already open a issue report on they plugin, but i also want to open here because idk if the error is part of they or here...
This is the issue report: https://github.com/BG-Software-LLC/SSB-SlimeWorldManager/issues/24

Well, the problem is when player try create a island, then SSW try create a world in SlimeWorld thing, but get this error

minecraft 1.19.4

**Comment by akcelerat0r** [comment]
I guess its because you dont setup the Modules...
If there is no datasource installed it will use slime format as file storage...
Is this you're error?
You can add me on Discord:
akcel#3644
