### ISSUE TITLE
Strange exceptions

### ISSUE THREAD

**Issue by swat1x** [Paul19988/Advanced-Slime-World-Manager#171]
Its finding all jars in server directory and throw exception.

(i have latest swm version)
![image](https://github.com/Paul19988/Advanced-Slime-World-Manager/assets/82226339/049c797e-5399-4524-8a7a-9839f97cbedb)

**Comment by Paul19988** [comment]
Remove the spaces from your directory

**Comment by swat1x** [comment]
> Remove the spaces from your directory

thanks!

![image](https://github.com/Paul19988/Advanced-Slime-World-Manager/assets/82226339/771abbac-636e-4da6-a503-372cea61793e)

**Comment by swat1x** [comment]
Now this exception
![image](https://github.com/Paul19988/Advanced-Slime-World-Manager/assets/82226339/7545f650-932b-4876-8bdc-0e9af140cd42)

**Comment by Paul19988** [comment]
What version is your server?

**Comment by swat1x** [comment]
> What version is your server?

1.18.2 Paper

![image](https://github.com/Paul19988/Advanced-Slime-World-Manager/assets/82226339/73ff0aa5-1a6b-4af8-8cce-ad649bca24dc)

**Comment by Paul19988** [comment]
Do your configs contain characters other than a-z A-Z?

**Comment by swat1x** [comment]
> Do your configs contain characters other than a-z A-Z?

After blue screen config files of plugin was broken. I delete and it fixed. Thanks!!
