### ISSUE TITLE
Hope to store ITEM_FRAM

### ISSUE THREAD

**Issue by inrhor** [Paul19988/Advanced-Slime-World-Manager#176]
**Is your feature request related to a problem? Please describe.**
Yes

**Describe the solution you'd like**
When I planted crops and restarted the server, the crops disappeared.

CustomCrops(ITEM_FRAME)
ItemsAdder

**Comment by akcelerat0r** [comment]
did you save the world via driver and bukkit unload methods?

**Comment by inrhor** [comment]
Revise it again and it can be saved. I'm sorry to bother you. Thanks
