### ISSUE TITLE
useSSL Configurable

### ISSUE THREAD

**Issue by Acixsi** [Paul19988/Advanced-Slime-World-Manager#18]
The MySQL Database we run doesn't have SSL enabled, unfortunately I can't disable the use of SSL right now in the SWM sources.yml. Because of this, my console get's spammed with warnings about not using SSL. It would be great if this would be a configurable option within sources.yml, I think I'm not the only one, not having a SSL MySQL Database. Thanks in advance!

**Comment by Paul19988** [comment]
Hi could you please clarify which version of ASWM you are using (This includes the branch)

**Comment by Acixsi** [comment]
I have your version installed on my server "Advanced-Slime-World-Manager" for 1.16.4. Because all our servers run on 1.16.4.

Need anything else? :)

**Comment by Paul19988** [comment]
https://github.com/Paul19988/Advanced-Slime-World-Manager/tree/feature/aswm/1.16.4

Latest push should do the trick 👍

**Comment by Acixsi** [comment]
Wow! Thanks for the extremely fast response and fix! My console isn't getting spammed with SSL warnings anymore. 👍

**Comment by Paul19988** [comment]
Awesome! Glad the fix worked and you're welcome ;)
