### ISSUE TITLE
Can't overwrite default worlds

### ISSUE THREAD

**Issue by BlueSoapTurtle** [Paul19988/Advanced-Slime-World-Manager#2]
**Describe the issue**
Can't overwrite default worlds

**Spigot version**
any

**Plugin version**
latest

**How to reproduce**
Make a world called "world" or the same as the default world in server.properties, it won't overwrite

We need to add the classmodifier file back for add_world and the default worlds back to the 1.16 nms class

**Comment by Paul19988** [comment]
Re-implemented but needs continued work, still does not override default world.

**Comment by BlueSoapTurtle** [comment]
Seems to be related to not creating a "temp_ + worldname" world to store the session.lock in

**Comment by BlueSoapTurtle** [comment]
Resolved
