### ISSUE TITLE
Allowmonsters and allowanimals setting not working, mobs still spawn

### ISSUE THREAD

**Issue by dxdejong** [Paul19988/Advanced-Slime-World-Manager#25]
**Describe the issue**
I have allowMonsters and allowAnimals set to false in the aswm config and mobs still spawn.
Gamerule also does not work, when I restart they are back again

**Spigot version**
PaperMC 1.16.4

**Plugin version**
plugin version 2.5.3 Snapchot

**How to reproduce**
Whenever it loads the world mobs are there.

**Crash reports (if available)**
none

**Comment by Paul19988** [comment]
Should be fixed with https://github.com/Paul19988/Advanced-Slime-World-Manager/commit/328979e5bff9786d843d313287f1edf980f61115

The latest jars can be found here: https://ci.rapture.pw/browse/ASWM-ASWM10-24/artifact/shared/output/

**Comment by dxdejong** [comment]
I tried, no luck.
Mobs still spawn

**Comment by dxdejong** [comment]
Any idea what else it could be?
