### ISSUE TITLE
EOFException when loading a single-biome world from singleplayer 1.16.5

### ISSUE THREAD

**Issue by OskarZyg** [Paul19988/Advanced-Slime-World-Manager#27]
**Describe the issue**
An java.io.EOFException occurs when loading a single-biome world from singleplayer. This world works when used with hyperverse and loaded on a server with no plugins, but SWM produces an error.

**Spigot version**
```
[20:40:58 INFO]: This server is running Tuinity version git-Tuinity-"502d57b" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[20:40:58 INFO]: Checking version, please wait...
[20:40:58 INFO]: You are running the latest version
```
**Plugin version**
```
[20:41:29 INFO]: SWM >> This server is running SWM v2.5.3-SNAPSHOT, which supports up to Slime Format v9.
```
**How to reproduce**
This is my world: https://drive.google.com/uc?id=10j9jrR-XM_DmA_xJUXDcGBC5ampwG-Zj
Try to import the world using /swm import

**Crash reports (if available)**
https://gist.githubusercontent.com/OskarZyg/8494d7e7c718df5a396e604c6e2f20c5/raw/6a59fcfee59dc2806dd37b1cad1dea22090866fe/latest.log

**Comment by Paul19988** [comment]
![image](https://user-images.githubusercontent.com/2083156/107888892-49e30100-6f07-11eb-8941-bbc6ae5af5ed.png)
Please review your worlds region folder as it appears to have corrupted files

**Comment by OskarZyg** [comment]
What do you mean by that? The world does load in singleplayer, tunity with no plugins and tunity with hyperverse.

**Comment by Paul19988** [comment]
Yes, regular Minecraft will be doing error correction, (A)SWM does not

**Comment by OskarZyg** [comment]
So what should I do?

**Comment by Paul19988** [comment]
Best course of action is to delete the region file which has 0 bytes size

**Comment by OskarZyg** [comment]
Great, that works, however now i get a ```
java.io.IOException: com.mysql.jdbc.PacketTooBigException: Packet for query is too large (27639171 > 16777216).
```
