### ISSUE TITLE
Playerheads won't save when on ArmorStand

### ISSUE THREAD

**Issue by Acixsi** [Paul19988/Advanced-Slime-World-Manager#31]
- Actual Playerheads will save whenever I place them as a "block" on the ground or against a wall. Actually whenever I place them on a **ArmorStand** to change the direction or height or something they won't get saved if the playerhead is a custom one with custom NBT Data (from for example minecraft-heads.com). Whenever it's a actual playerhead from a real player they do get saved.

- Running Paper 1.16.5 b551

- Running ASWM 2.5.3 (Build #19 from the Develop branche on ci.rapture.pw)

- Actually already described how to reproduce in my problem text.

- Luckily NO crash reports. :D

**Comment by Paul19988** [comment]
Fixed in e006541b969df085ab200bc5276ff77b687b21cf
