### ISSUE TITLE
Cannot clone/load world from file.

### ISSUE THREAD

**Issue by levahmc** [Paul19988/Advanced-Slime-World-Manager#35]
I cannot seem to clone/migrate a world from file.
<img width="654" alt="Screenshot 2021-04-25 at 03 20 42" src="https://user-images.githubusercontent.com/52663439/115978102-39897b00-a575-11eb-87dd-23b3cdba7cc1.png">

Purpur 1.16.5

ASWM-2.5.3-Snapshot

No errors in console.

**Comment by Paul19988** [comment]
Possibly fixed, please test again with 2.6.2
