### ISSUE TITLE
the configuration bugs.

### ISSUE THREAD

**Issue by portlek** [Paul19988/Advanced-Slime-World-Manager#45]
if you run the plugin first time, you will get a main.yml file with only contains `null` keyword, and your console will print error about null pointer exception in this line;

https://github.com/Paul19988/Advanced-Slime-World-Manager/blob/develop/slimeworldmanager-plugin/src/main/java/com/grinderwolf/swm/plugin/SWMPlugin.java#L134

because this method getUpdaterOptions() returns null.

to solve the issue, there are 2 choices

1- change the configuration library to more reliable one
2- update the current configuration library to the new one. this is easier than the first choice.

**Comment by portlek** [comment]
no one cares, even i fixed, anyways.

**Comment by Paul19988** [comment]
> no one cares, even i fixed, anyways.

It was declined in favour of a new system being developed, do not be aggressive towards anybody on this project, it is maintained for FREE and in our SPARE time.
