### ISSUE TITLE
Dependency "flow-nbt-2.0.0" Doesn't Exist Anymore

### ISSUE THREAD

**Issue by SirCodalot** [Paul19988/Advanced-Slime-World-Manager#88]
**Describe the issue**
This isn't a bug in ASWM but it still prevents developers from using the API. I am using ASWM's API in my Gradle project and everything was working fine. Today I tried to build my project and got an error that says `Could not find com.flowpowered:flow-nbt-2.0.0:2.0.0.`. I looked for the dependency in https://repo.maven.apache.org/maven2/com/flowpowered/ and it looks like it was either moved or completely removed.

**How to reproduce**
If the dependency was removed, you should get the same error when building ASWM with Maven.

**Comment by b0ykoe** [comment]
Sorry to cause inconvenience for you. The repo you're talking about was removed ages ago. We've reuploaded flow-nbt:2.0.0 in June to our repo.

https://repo.rapture.pw/#browse/browse:maven-releases:com%2Fflowpowered
