### ISSUE TITLE
Normal world creation thorugh the API

### ISSUE THREAD

**Issue by ukeo** [Paul19988/Advanced-Slime-World-Manager#89]
**Is your feature request related to a problem? Please describe.**
I'm currently coding a minigame where you can play minecraft thorugh. And I want to use the API to create 3 normal worlds like vanilla. But as a saw this is currently not possible with the api.

**Describe the solution you'd like**
A method to create vanilla worlds in the api.

**Comment by Paul19988** [comment]
That isn't possible with A(SWM).... That's not how this software works; it does not support vanilla worlds intentionally.

**Comment by Meldiron** [comment]
You could pre-generate thousands of Minecraft worlds, then convert them into SLIME format. Players would never notice and you can pre-generate new ones anytime.

**Comment by Acixsi** [comment]
@Meldiron A(SWM) is not meant to work for normal Minecraft worlds. I get what you're saying, but the SLIME system is meant to be used for small worlds like minigames or lobby's, with a maximum radius of blocks, not a infinite amount.
