### ISSUE TITLE
rror 526 Invalid SSL certificate

### ISSUE THREAD

**Issue by samfces** [Paul19988/Advanced-Slime-World-Manager#90]
**Describe the issue**
When I try to go to build server's web page, error 526 is shown.

**Spigot version**

**Plugin version**

**How to reproduce**
1. Open https://ci.rapture.pw/artifact/ASWM-ASWM10/shared/build-29/output/slimeworldmanager-plugin/target

**Crash reports (if available)**

**Comment by b0ykoe** [comment]
That domain is not used for about 4 months now. 
Buildserver: https://teamcity.rapture.pw/
Downloadpage: https://dl.rapture.pw/
Repo: https://repo.skira.org/

Discord, can be used to find the latest builds, https://discord.gg/SppVZcv9vR
