### ISSUE TITLE
Plugin generates null main config

### ISSUE THREAD

**Issue by exzolink** [Paul19988/Advanced-Slime-World-Manager#92]
**Describe the issue**
Plugin generates null main config

**Spigot version**
Airplane 1.16.5

**Plugin version**
2.6.2

**How to reproduce**
Just install plugin and start server

**Crash reports (if available)**

**Comment by Paul19988** [comment]
[Slime-World-Manager270-1.16.5.zip](https://github.com/Paul19988/Advanced-Slime-World-Manager/files/7831698/Slime-World-Manager270-1.16.5.zip)
Use this version.

**Comment by exzolink** [comment]
Thank you!
