### ISSUE TITLE
Missing SlimePropertyMap.fromCompound(CompoundTag)

### ISSUE THREAD

**Issue by MrEAlderson** [Paul19988/Advanced-Slime-World-Manager#94]
**Is your feature request related to a problem? Please describe.**
Kinda. This method exists with the original SWM, but not for this variant for whatever reason. This caused an error within my plugin, that relies on your API.

**Describe the solution you'd like**
Re-adding the method.
I've currently solved this with reflection, but this should be a part of the API, really. It doesn't make sense that you're able to serialize a CompoundTag, however not able to do the reverse process of deserializing it again.

**Comment by Paul19988** [comment]
Just use the original API if you're using the original plugin? This isn't our problem.
