### ISSUE TITLE
Fixed release for 1.16?

### ISSUE THREAD

**Issue by CommandDan** [Paul19988/Advanced-Slime-World-Manager#96]
*Missunderstood how it worked*

**Comment by Paul19988** [comment]
https://cdn.discordapp.com/attachments/741734887538688092/928722829703270470/slimeworldmanager-plugin-2.7.0-SNAPSHOT.jar
https://cdn.discordapp.com/attachments/741734887538688092/928722830936387645/slimeworldmanager-classmodifier-2.7.0-SNAPSHOT.jar

Use this for 1.16.5

**Comment by CommandDan** [comment]
Thank you, though it doesn't seem to load properly on our server for some reason. Does the project have a Discord btw?

**Comment by CommandDan** [comment]
Nvm why did I just ask that...

**Comment by ComputerNerd100** [comment]
> Thank you, though it doesn't seem to load properly on our server for some reason. Does the project have a Discord btw?

@CommandDan https://discord.gg/YevvsMa
Feel free to tag me in there (@ComputerNerd100) and chuck any error messages you're getting etc. at me and I'll see what I can figure out :)
